[tool.poetry]
name = "ann-plotter"
version = "1.1.0"  # Updated version

[tool.poetry.dependencies]
matplotlib = "^3.10.0"
networkx = "^3.4.2"
numpy = "^1.26.4"
plotly = "^5.0"  # Alternative to d3py
